### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wiseaidev** [wiseaidev/wiseai.dev#3]
- [ ] Landing Page
- [ ] Blog Frontend
- [ ] Blog Backend (MongoDB + Rocket?)
- [ ] SEO Optimization.
- [ ] Images Optimization.
- [ ] Use [Tailwind CLI](https://tailwindcss.com/docs/installation) instead of the tailwind `script` tag once website is fully developed. The reason for using this tag now is for faster development/compilation.
 https://github.com/wiseaidev/wiseai.dev/blob/0b8b259084e31c2de493a8501c835aad82d9168e/index.html#L106
- [ ] Decouple data from UI (Move to json files?).
